In [2]:
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
import matplotlib as plt
%matplotlib inline

In [3]:
def get_data():
    iris_data = datasets.load_digits()
    data = iris_data.data
    targets = iris_data.target
    X_train, X_test, y_train, y_test = train_test_split(data,targets,test_size=0.2)
    return (X_train, X_test, y_train, y_test)

In [4]:
X_train, X_test, y_train, y_test = get_data()

In [5]:
get_data()

(array([[ 0.,  0.,  1., ..., 16., 13.,  3.],
        [ 0.,  0.,  9., ...,  3.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  4., ...,  0.,  0.,  0.],
        [ 0.,  0., 12., ..., 15.,  6.,  0.],
        [ 0.,  0.,  4., ...,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  4., ...,  8.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  7., ..., 11.,  3.,  0.],
        ...,
        [ 0.,  1., 15., ..., 16., 16.,  5.],
        [ 0.,  0.,  1., ..., 12.,  7.,  0.],
        [ 0.,  0.,  7., ...,  5.,  0.,  0.]]),
 array([3, 0, 7, ..., 8, 9, 7]),
 array([0, 4, 3, 8, 4, 1, 5, 3, 5, 6, 7, 6, 2, 9, 3, 1, 4, 7, 9, 4, 5, 4,
        1, 3, 5, 5, 9, 6, 7, 4, 2, 2, 3, 5, 1, 9, 6, 0, 6, 8, 6, 0, 5, 4,
        1, 4, 5, 7, 6, 9, 5, 8, 4, 4, 9, 5, 0, 0, 9, 1, 4, 6, 0, 9, 2, 1,
        5, 6, 1, 8, 3, 6, 4, 9, 5, 7, 7, 4, 9, 7, 0, 1, 7, 6, 1, 9, 5, 9,
        0, 4, 2, 4, 2, 4, 6, 2, 6, 9, 6, 3, 8, 7, 1, 4, 6, 1, 3, 6, 2, 5,
        9, 8, 6, 8, 5, 8, 0

# Implementation of Logistic Regression without external libraries

In [9]:
def sigmoid(Z):
    #implement the sigmoid activation of the function (~1 Line of Code)
    A = None # 
    assert(a.shape == Z.shape)
    return A



In [10]:
def Output(W,b,X):
    assert(W.shape[1] == X.shape[0])
    assert(W.shape[0] == b.shape[0])
    #imlpement the output of the node before activation (~1 Line of Code)
    Z = None # this is the output before the activation function Z = W'.X+b
    
    assert(b.shape == Z.shape)
    return Z

In [11]:
def activated_Output(W,b,X):
    #Your code Here (~2 Line of Code)
    Z = None # this is the output before activation
    A = None # this is the final output of the logistic Unit
    
    assert(X.shape == Z.shape)
    assert(Z.shape == A.shape)
    return A

In [12]:
def compute_Cost(W,b,X,Y):
    A = activated_Output(W,b,X)
    #Your code here (~1 Line of Code)
    cost = None
    
    assert(cost.shape == A.shape)
    return cost


In [15]:
def get_Gradients(W,b,X,Y):
    cost  = compute_Cost(W,b,X,Y)
    weights_cost = None 
    bias_cost = None 
    
    assert(weights_cost.shape == W.shape)
    assert(bias_cost.shape == b.shape)
    return weights_cost,bias_cost

In [16]:
def calculate_gradient_for_one_pass(W,b,X,Y,learning_rate):
    dW,db = get_Gradients(W,b,X,Y)
    #your code here
    new_W = None
    new_b = None
    
    assert(new_W.shape == W.shape)
    assert(new_b.shape == b.shape)
    W = new_W
    b = new_b
    return W,b


In [ ]:
def Train_Model(X_train, y_train):
    #initialize the weights and bias
    X_train = X_train.reshape(-1)
    W = np.ones((X_train.shape),1) #weights
    b = np.ones(X_train.shape) #bias