In [1]:
# import statement for numpy
import numpy as np

# Creation of np array

In [2]:
#static creation of np array from list
list_a = [[1],[2],[3]]
a = np.array(list_a)
print (a)
print (a.dtype)
print (a.astype(np.float64))
print (a.shape)

[[1]
 [2]
 [3]]
int64
[[1.]
 [2.]
 [3.]]
(3, 1)


In [3]:
#Saving the array as a np object
np.save('arrayA.npy',a)
#loading the array 
loadedA = np.load('arrayA.npy')
loadedA

array([[1],
       [2],
       [3]])

In [4]:
# 2d arrays
list_b = [[1,0,0],
     [0,1,0],
     [0,0,1]]
b = np.array(list_b)
print (b)
print (type(b))
print (b.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
<type 'numpy.ndarray'>
(3, 3)


In [5]:
#To create 0's and 1's array
zeroArray = np.zeros((2,3))
oneArray = np.ones((3,4))
print (zeroArray)
print (oneArray)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# generating Random numbers
c = np.random.randint(low=1,high=10,size=(3,3))
d = np.random.rand(8,3)
e = np.random.random_sample((3,4))
print (c)
print (d)
print (e)

[[4 6 3]
 [8 5 1]
 [4 2 1]]
[[0.95278851 0.35628495 0.97239551]
 [0.6761344  0.4573056  0.70934387]
 [0.89858604 0.01403811 0.31495416]
 [0.67106876 0.50156959 0.76877632]
 [0.20474398 0.23414926 0.85967869]
 [0.53039706 0.31683287 0.4351485 ]
 [0.67044106 0.49544652 0.99324072]
 [0.28909138 0.99700248 0.15912253]]
[[0.43296482 0.2321129  0.0936585  0.17977703]
 [0.96125375 0.68158213 0.68476518 0.72865113]
 [0.97281387 0.98780085 0.29543261 0.4017331 ]]


In [7]:
#basic math operations
#Add
print (np.add(c,c.T))

#Subtract
print (c.T - c)

[[ 8 14  7]
 [14 10  3]
 [ 7  3  2]]
[[ 0  2  1]
 [-2  0  1]
 [-1 -1  0]]


In [8]:
#dot product
print (np.dot(b,c))

# element wise multiplication
print (a*b)

[[4 6 3]
 [8 5 1]
 [4 2 1]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [9]:
#div
print (c/a)

[[4 6 3]
 [4 2 0]
 [1 0 0]]


In [10]:
#Higher math operations
#logarithm
print (np.log(c))

#exp : e^(input), e is the natural logarithm's base
print (np.exp(a))

[[1.38629436 1.79175947 1.09861229]
 [2.07944154 1.60943791 0.        ]
 [1.38629436 0.69314718 0.        ]]
[[ 2.71828183]
 [ 7.3890561 ]
 [20.08553692]]


In [11]:
#check out trignometric operations as well

# comparison Operator

In [12]:
print (c)
# .T will return the transpose
# the equality check
print (c == c.T)

[[4 6 3]
 [8 5 1]
 [4 2 1]]
[[ True False False]
 [False  True False]
 [False False  True]]


In [13]:
# Inequality check
c <= 4 

array([[ True, False,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [14]:
#indexing
c[c<=4]

array([4, 3, 1, 4, 2, 1])

# slicing & subsetting

In [15]:

#print all rows in the first column
print (c[:,1])
#print all the rows but the last one
print (c[:-1,:])

[6 5 2]
[[4 6 3]
 [8 5 1]]


In [16]:
#reversing the order
a[::-1]

array([[3],
       [2],
       [1]])

In [17]:
#generate evenly spaced numbers over a specified interval.
f = np.linspace(start=0,stop=8,num=9)
f

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [18]:
f = np.array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

print (f)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [19]:
#reversing all rows and columns
f[::-1]

array([[6., 7., 8.],
       [3., 4., 5.],
       [0., 1., 2.]])

In [20]:
#fancy indexing
print (f[[0,1,2],[1,2,0]])

#why?
print (f[[0,1,2]])
print (f[0,1],f[1,2],f[2,0])

[1. 5. 6.]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(1.0, 5.0, 6.0)


# Reshaping array

In [21]:
#reshaping arrays into required shape
d_1 = np.reshape(d,newshape=(6,4))
# in order to reshape the 8x3 into 6x4, size can also be mentioned as 6,-1; 
# the compiler auto computes the remaining factor in place of -1
d_2 = d.reshape((6,-1))
print (d_1)
print (d_2)
print (d_1 == d_2)

[[0.95278851 0.35628495 0.97239551 0.6761344 ]
 [0.4573056  0.70934387 0.89858604 0.01403811]
 [0.31495416 0.67106876 0.50156959 0.76877632]
 [0.20474398 0.23414926 0.85967869 0.53039706]
 [0.31683287 0.4351485  0.67044106 0.49544652]
 [0.99324072 0.28909138 0.99700248 0.15912253]]
[[0.95278851 0.35628495 0.97239551 0.6761344 ]
 [0.4573056  0.70934387 0.89858604 0.01403811]
 [0.31495416 0.67106876 0.50156959 0.76877632]
 [0.20474398 0.23414926 0.85967869 0.53039706]
 [0.31683287 0.4351485  0.67044106 0.49544652]
 [0.99324072 0.28909138 0.99700248 0.15912253]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [22]:
# Task : try to reshape the array into a 3d array of dimension 2x3x4

# Deletion of elements

In [23]:
# deletion of rows/cols
d_colDelete = np.delete(d,1,axis = 1)
d_rowDelete = np.delete(d,2,axis = 0)
print (d_colDelete.shape)
print (d_rowDelete.shape)

(8, 2)
(7, 3)


In [24]:
# Learn the concepts of axis properly. Look up stackoverflow or any python documentation

In [25]:
# delete a particular element of array c
# also try out inserting an element and appending an element 

# Merging Rows / Columns

In [26]:
# mergeing rows/cols
mergeRows = np.vstack((c,d))
mergeCols = np.hstack((c,e))

In [27]:
print (mergeRows)

[[4.         6.         3.        ]
 [8.         5.         1.        ]
 [4.         2.         1.        ]
 [0.95278851 0.35628495 0.97239551]
 [0.6761344  0.4573056  0.70934387]
 [0.89858604 0.01403811 0.31495416]
 [0.67106876 0.50156959 0.76877632]
 [0.20474398 0.23414926 0.85967869]
 [0.53039706 0.31683287 0.4351485 ]
 [0.67044106 0.49544652 0.99324072]
 [0.28909138 0.99700248 0.15912253]]


In [28]:
print (mergeCols)

[[4.         6.         3.         0.43296482 0.2321129  0.0936585
  0.17977703]
 [8.         5.         1.         0.96125375 0.68158213 0.68476518
  0.72865113]
 [4.         2.         1.         0.97281387 0.98780085 0.29543261
  0.4017331 ]]


In [29]:
# Task: look up np.concatenate and do the above performed operations using it 

# Few tasks on np using aggregate functions

In [30]:
minRowC = np.min(c,axis=1)
avgColD = np.mean(d,axis=0)
print (c)
print 'Row Min:',minRowC
print ('---------------------')
print (d)
print 'Col Avg:',avgColD

[[4 6 3]
 [8 5 1]
 [4 2 1]]
Row Min: [3 1 1]
---------------------
[[0.95278851 0.35628495 0.97239551]
 [0.6761344  0.4573056  0.70934387]
 [0.89858604 0.01403811 0.31495416]
 [0.67106876 0.50156959 0.76877632]
 [0.20474398 0.23414926 0.85967869]
 [0.53039706 0.31683287 0.4351485 ]
 [0.67044106 0.49544652 0.99324072]
 [0.28909138 0.99700248 0.15912253]]
Col Avg: [0.6116564  0.42157867 0.65158254]


In [31]:
# find the row wise mean of array e
# find the max of all the values in the array c
# median of array f
# cumulative sum of a

In [32]:
# sort each column
np.sort(c,axis=0)

array([[4, 2, 1],
       [4, 5, 1],
       [8, 6, 3]])